server:
  interface: 0.0.0.0
  port: 53
  do-ip4: yes
  do-ip6: no
  do-tcp: yes
  access-control: 0.0.0.0/0 allow
  module-config: "iterator"
  use-caps-for-id: no
  outgoing-range: 1
  outgoing-port-avoid: 1024-65535
  outgoing-port-permit: 33333
  verbosity: 5
  use-syslog: no
  log-time-ascii: yes
  log-queries: yes
  log-replies: yes
  log-servfail: yes

stub-zone:
  name: "."
  stub-addr: 172.30.0.10@53

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  control-use-cert: no
